### PR TITLE
fix all data issues

### PR DESCRIPTION
**Pull request by davidpeden3**

### CODE REVIEW

**Comment by davidpeden3** [comment]
@pvpoke ok, i've updated the pr to have the latest changes. should be good to merge now.

**Comment by pvpoke** [comment]
Thanks for all the work on this! The main thing I noticed was that most of the fast moves don't appear to have a cooldown value:

`
    {
      "moveId": "FURY_CUTTER",
      "name": "Fury Cutter",
      "type": "bug",
      "power": 2,
      "energy": 0,
      "energyGain": 4
    }
`

A second minor thing I want to add is that [per this issue](https://github.com/pvpoke/pvpoke/issues/12), Mr. Mime's `speciesID` should be `mr_mime` instead of `mr. mime`. Thanks for the special attention to keeping the old speciesID's, though!

**Comment by davidpeden3** [comment]
Oh, interesting. I'm not sure how I missed that. Ok, I will have to go back to harvesting that from the PVE move because it's not physically in the PVP move data.

```json
    {
      "templateId": "COMBAT_V0200_MOVE_FURY_CUTTER_FAST",
      "combatMove": {
        "uniqueId": "FURY_CUTTER_FAST",
        "type": "POKEMON_TYPE_BUG",
        "power": 2.0,
        "vfxName": "fury_cutter_fast",
        "energyDelta": 4
      }
    },
```

and

```json
    {
      "templateId": "V0200_MOVE_FURY_CUTTER_FAST",
      "moveSettings": {
        "movementId": "FURY_CUTTER_FAST",
        "animationId": 4,
        "pokemonType": "POKEMON_TYPE_BUG",
        "power": 3.0,
        "accuracyChance": 1.0,
        "staminaLossScalar": 0.01,
        "trainerLevelMin": 1,
        "trainerLevelMax": 100,
        "vfxName": "fury_cutter_fast",
        "durationMs": 400,
        "damageWindowStartMs": 100,
        "damageWindowEndMs": 400,
        "energyDelta": 6
      }
    },
```

Regarding the change to Mr. Mime, that's an easy deletion of a [special case](https://github.com/davidpeden3/pvpoke-gamemaster-adapter/blob/master/Test/PvPoke.UnitTest/FileManagerTests.cs#L293-L295) that was added to maintain your file format. ;)

Take a look at that block and see if you agree that all those cases should go away and that they should exclusively live in [GenerateSpeciesName](https://github.com/davidpeden3/pvpoke-gamemaster-adapter/blob/master/Test/PvPoke.UnitTest/FileManagerTests.cs#L304).

**Comment by pvpoke** [comment]
Yeah, it makes sense that those could go in GenerateSpeciesName!

I peeked at the original gamemaster and it looks like all fast moves that don't have `durationTurns` defined have a `durationTurns` value of 0 (includes Water Gun, Fury Cutter, Bite, Cut, etc.). I hope that's helpful!

**Comment by pvpoke** [comment]
Correct! There's no reason to double the values anymore, that was just a mistake I made when originally handling the values, so you can just do `(0 turns + 1 turn) * 500ms`.

**Comment by pvpoke** [comment]
I've checked and tested this locally, and everything looks great now! I'm going to rerun the rankings to make sure everything lines up. I'll look to get this merged later today!

**Comment by davidpeden3** [comment]
Awesome. Now that this is done, I'll look into automating a trigger for submitting PRs to you. ;)

**Pull request merged**
