### PR TITLE
Season 3 Move Changes

### PR DESCRIPTION
**Pull request by alexameen**
I think that I recalculated rankings correctly, but someone might want to sanity check it.

### CODE REVIEW

**Comment by pvpoke** [comment]
Hey Alex, I really, really appreciate the work you put into this. Sorry I haven't been able to respond to the issues you encountered while putting this update together. I already have these updates made locally and am currently tweaking the rankings and movesets ahead of release, so unfortunately I'm unable to use your work.

I'm sorry this didn't work out this time, but feel free to reach out to me when you'd like to contribute and we can coordinate future updates and releases.

**Comment by alexameen** [comment]
> Hey Alex, I really, really appreciate the work you put into this. Sorry I haven't been able to respond to the issues you encountered while putting this update together. I already have these updates made locally and am currently tweaking the rankings and movesets ahead of release, so unfortunately I'm unable to use your work.
> 
> I'm sorry this didn't work out this time, but feel free to reach out to me when you'd like to contribute and we can coordinate future updates and releases.

Bummer. In any case it was a good exercise for me to do.

I just edited my original comment to list the things I did to recalculate the rankings. Would you mind taking a look at them to see if I did things correctly?

**Comment by pvpoke** [comment]
I want to say I'm really impressed you figured out the ranking process because it's honestly pretty messy.

`ranker.php` is run before `rankersandbox.php` but I checked your results and they looked pretty close to what I already had, so great work there! I have a lot of work I'd like to do with streamlining the ranking process.

**Comment by alexameen** [comment]
> I want to say I'm really impressed you figured out the ranking process because it's honestly pretty messy.
> 
> `ranker.php` is run before `rankersandbox.php` but I checked your results and they looked pretty close to what I already had, so great work there! I have a lot of work I'd like to do with streamlining the ranking process.

I'm noticing the actual rankings don't use the "new best" move-sets, I'm assuming those are set by `data/group/<FOO>.json`. Do you edit those by hand or is there a script to figure those out? And I also noticed that I missed adding the new moves to Shadow forms. Ex: Abomasnow has Weather Ball listed as a charged move but Shadow Abomasnow doesn't.

**Pull request closed without merging**
